from enum import Enum


class EventType(str, Enum):
    USER_REGISTERED = "USER_REGISTERED"
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_DELETED = "PROJECT_DELETED"
    GOOGLE_ACCOUNT_CONNECTED = "GOOGLE_ACCOUNT_CONNECTED"
    GOOGLE_CONFERENCE_SYNCED = "GOOGLE_CONFERENCE_SYNCED"
