from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = "007_create_workspace_ai_tables"
down_revision = "006_create_knowledge_chunks"
branch_labels = None
depends_on = None
def upgrade():
    op.create_table("workspace_memory", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("category", sa.String(80), nullable=False), sa.Column("value", sa.Text(), nullable=False), sa.Column("confidence_score", sa.Float(), nullable=False), sa.Column("source", sa.String(80), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE")); op.create_index("ix_workspace_memory_workspace_id", "workspace_memory", ["workspace_id"])
    op.create_table("workspace_documents", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("project_id", postgresql.UUID(as_uuid=True)), sa.Column("meeting_id", postgresql.UUID(as_uuid=True)), sa.Column("file_name", sa.String(255), nullable=False), sa.Column("content_type", sa.String(100), nullable=False), sa.Column("extracted_text", sa.Text(), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["project_id"], ["projects.id"]), sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"]), sa.ForeignKeyConstraint(["created_by"], ["users.id"])); op.create_index("ix_workspace_documents_workspace_id", "workspace_documents", ["workspace_id"])
    op.create_table("playbooks", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("name", sa.String(150), nullable=False), sa.Column("domain", sa.String(100), nullable=False), sa.Column("typical_requirements", postgresql.JSONB(), nullable=False), sa.Column("recommended_features", postgresql.JSONB(), nullable=False), sa.Column("common_integrations", postgresql.JSONB(), nullable=False), sa.Column("security_checklist", postgresql.JSONB(), nullable=False), sa.Column("deployment_checklist", postgresql.JSONB(), nullable=False), sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["created_by"], ["users.id"])); op.create_index("ix_playbooks_workspace_id", "playbooks", ["workspace_id"])
    op.create_table("playbook_questions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("playbook_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("question", sa.Text(), nullable=False), sa.Column("reason", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["playbook_id"], ["playbooks.id"], ondelete="CASCADE")); op.create_index("ix_playbook_questions_playbook_id", "playbook_questions", ["playbook_id"])
def downgrade():
    op.drop_table("playbook_questions"); op.drop_table("playbooks"); op.drop_table("workspace_documents"); op.drop_table("workspace_memory")
