import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import api from '../lib/api'

type DocumentItem = { id: string; meeting_id: string; document_type: string; title: string; content: string; version: number; status: string; created_at: string }
const types = [['srs', 'SRS'], ['brd', 'BRD'], ['mom', 'Meeting Minutes'], ['client_summary', 'Client Summary'], ['technical', 'Technical Requirements']]

export default function Documentation() {
  const queryClient = useQueryClient(); const [projectId, setProjectId] = useState(''); const [meetingId, setMeetingId] = useState(''); const [kind, setKind] = useState('srs'); const [selected, setSelected] = useState<DocumentItem | null>(null); const [error, setError] = useState('')
  const documents = useQuery({ queryKey: ['documents', projectId], queryFn: async () => (await api.get<DocumentItem[]>(`/api/v1/documents/${projectId}`)).data, enabled: Boolean(projectId), retry: false })
  const generate = useMutation({ mutationFn: async () => (await api.post<DocumentItem>(`/api/v1/documents/generate/${meetingId}`, { document_type: kind })).data, onSuccess: (item) => { queryClient.invalidateQueries({ queryKey: ['documents', projectId] }); setSelected(item); setError('') }, onError: () => setError('Unable to generate the document. Confirm the meeting and project IDs and that you have access.') })
  const approve = useMutation({ mutationFn: async (id: string) => (await api.patch<DocumentItem>(`/api/v1/document/${id}`, { status: 'approved' })).data, onSuccess: (item) => { setSelected(item); queryClient.invalidateQueries({ queryKey: ['documents', projectId] }) } })
  const remove = useMutation({ mutationFn: async (id: string) => api.delete(`/api/v1/document/${id}`), onSuccess: () => { setSelected(null); queryClient.invalidateQueries({ queryKey: ['documents', projectId] }) } })
  const download = async (item: DocumentItem, format: string) => { const response = await api.get(`/api/v1/document/${item.id}/export/${format}`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = Object.assign(document.createElement('a'), { href: url, download: `${item.title}.${format}` }); link.click(); URL.revokeObjectURL(url) }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Documentation</h1><p className="mt-2 text-sm text-slate-600">Generate versioned project documents from approved AI requirements and meeting context.</p></div><section className="rounded-lg border bg-white p-4"><div className="grid gap-3 md:grid-cols-3"><input className="rounded border px-3 py-2" placeholder="Project ID" value={projectId} onChange={(e) => setProjectId(e.target.value)} /><input className="rounded border px-3 py-2" placeholder="Meeting ID" value={meetingId} onChange={(e) => setMeetingId(e.target.value)} /><select className="rounded border px-3 py-2" value={kind} onChange={(e) => setKind(e.target.value)}>{types.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><button className="mt-3 rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50" disabled={!meetingId || generate.isPending} onClick={() => generate.mutate()}> {generate.isPending ? 'Generating...' : 'Generate document'} </button>{error && <p className="mt-2 text-sm text-red-600">{error}</p>}</section><div className="grid gap-6 lg:grid-cols-[1fr_2fr]"><section className="rounded-lg border bg-white p-4"><h2 className="font-semibold">Generated documents</h2><div className="mt-3 space-y-2">{documents.data?.map((item) => <button key={item.id} className="w-full rounded border p-3 text-left hover:bg-slate-50" onClick={() => setSelected(item)}><p className="font-medium">{item.title} v{item.version}</p><p className="text-xs uppercase text-slate-500">{item.document_type} · {item.status}</p></button>) || <p className="text-sm text-slate-500">Enter a project ID to view documents.</p>}</div></section><section className="rounded-lg border bg-white p-4"><h2 className="font-semibold">Preview</h2>{selected ? <><div className="mt-3 flex flex-wrap gap-2"><button className="rounded border px-2 py-1 text-sm" onClick={() => approve.mutate(selected.id)}>Approve</button><button className="rounded border px-2 py-1 text-sm" onClick={() => generate.mutate()}>Regenerate</button>{['pdf', 'docx', 'markdown'].map((format) => <button key={format} className="rounded border px-2 py-1 text-sm" onClick={() => download(selected, format)}>{format.toUpperCase()}</button>)}<button className="rounded border px-2 py-1 text-sm text-red-700" onClick={() => remove.mutate(selected.id)}>Delete</button></div><pre className="mt-4 whitespace-pre-wrap font-sans text-sm text-slate-700">{selected.content}</pre></> : <p className="mt-3 text-sm text-slate-500">Select a document to preview it.</p>}</section></div></div>
}
