import { useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import api from '../lib/api'

type Result = { text: string; metadata: { source_type: string; meeting_id?: string }; score: number }
type Memory = { project_name: string; chunk_count: number; memory: Record<string, string[]> }

export default function KnowledgeBase() {
  const [projectId, setProjectId] = useState(''); const [meetingId, setMeetingId] = useState(''); const [query, setQuery] = useState(''); const [results, setResults] = useState<Result[]>([]); const [message, setMessage] = useState('')
  const memory = useQuery({ queryKey: ['project-memory', projectId], queryFn: async () => (await api.get<Memory>(`/api/v1/rag/project-memory/${projectId}`)).data, enabled: Boolean(projectId), retry: false })
  const index = useMutation({ mutationFn: async () => (await api.post<{ indexed_chunks: number }>(`/api/v1/rag/index/${meetingId}`)).data, onSuccess: (data) => { setMessage(`Indexed ${data.indexed_chunks} knowledge chunks.`); memory.refetch() }, onError: () => setMessage('Indexing failed. Verify the meeting ID and access permissions.') })
  const search = useMutation({ mutationFn: async () => (await api.post<Result[]>('/api/v1/rag/search', { project_id: projectId, query })).data, onSuccess: (data) => { setResults(data); setMessage('') }, onError: () => setMessage('Search failed. Enter a valid project ID and query.') })
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Knowledge Base</h1><p className="mt-2 text-sm text-slate-600">Index project knowledge and retrieve relevant context from previous discovery work.</p></div><section className="rounded-lg border bg-white p-4"><div className="grid gap-3 md:grid-cols-2"><input className="rounded border px-3 py-2" placeholder="Project ID" value={projectId} onChange={(event) => setProjectId(event.target.value)} /><div className="flex gap-2"><input className="w-full rounded border px-3 py-2" placeholder="Meeting ID to index" value={meetingId} onChange={(event) => setMeetingId(event.target.value)} /><button className="rounded bg-slate-900 px-3 py-2 text-white disabled:opacity-50" disabled={!meetingId || index.isPending} onClick={() => index.mutate()}>{index.isPending ? 'Indexing...' : 'Index meeting'}</button></div></div>{message && <p className="mt-2 text-sm text-slate-600">{message}</p>}</section><section className="rounded-lg border bg-white p-4"><h2 className="font-semibold">Semantic search</h2><div className="mt-3 flex gap-2"><input className="w-full rounded border px-3 py-2" placeholder="Have we discussed authentication before?" value={query} onChange={(event) => setQuery(event.target.value)} /><button className="rounded bg-slate-900 px-3 py-2 text-white disabled:opacity-50" disabled={!projectId || query.length < 2 || search.isPending} onClick={() => search.mutate()}>{search.isPending ? 'Searching...' : 'Search'}</button></div><div className="mt-4 space-y-3">{results.map((result, index) => <article key={index} className="rounded border p-3"><p className="text-xs uppercase text-slate-500">{result.metadata.source_type} · {Math.round(result.score * 100)}% relevance</p><p className="mt-1 text-sm text-slate-700">{result.text}</p></article>)}</div></section><section className="rounded-lg border bg-white p-4"><h2 className="font-semibold">Project memory</h2>{memory.data ? <><p className="mt-2 text-sm text-slate-600">{memory.data.project_name} · {memory.data.chunk_count} indexed chunks</p><div className="mt-4 grid gap-4 md:grid-cols-2">{Object.entries(memory.data.memory).map(([source, chunks]) => <div key={source}><h3 className="font-medium capitalize">{source.replaceAll('_', ' ')}</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{chunks.map((chunk, index) => <li key={index}>{chunk.slice(0, 180)}{chunk.length > 180 ? '…' : ''}</li>)}</ul></div>)}</div></> : <p className="mt-3 text-sm text-slate-500">Enter a project ID to view indexed meetings, documents, and knowledge chunks.</p>}</section></div>
}
