import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import api from '../lib/api'

type Memory = { id: string; category: string; value: string; confidence_score: number; source: string }
type Upload = { id: string; file_name: string; status: string; created_at: string }
type Playbook = { id: string; name: string; domain: string; typical_requirements: string[]; recommended_features: string[] }

export default function WorkspaceIntelligence() {
  const client = useQueryClient(); const [file, setFile] = useState<File | null>(null); const [meetingId, setMeetingId] = useState(''); const [playbookName, setPlaybookName] = useState(''); const [domain, setDomain] = useState(''); const [message, setMessage] = useState('')
  const memory = useQuery({ queryKey: ['workspace-memory'], queryFn: async () => (await api.get<Memory[]>('/api/v1/workspace/memory')).data })
  const documents = useQuery({ queryKey: ['workspace-documents'], queryFn: async () => (await api.get<Upload[]>('/api/v1/workspace/documents')).data })
  const playbooks = useQuery({ queryKey: ['playbooks'], queryFn: async () => (await api.get<Playbook[]>('/api/v1/playbooks')).data })
  const upload = useMutation({ mutationFn: async () => { const body = new FormData(); if (file) body.append('file', file); return api.post('/api/v1/workspace/upload', body, { headers: { 'Content-Type': 'multipart/form-data' } }) }, onSuccess: () => { client.invalidateQueries({ queryKey: ['workspace-documents'] }); setMessage('Knowledge document indexed successfully.'); setFile(null) }, onError: () => setMessage('Upload failed. Use PDF, DOCX, TXT, or Markdown.') })
  const create = useMutation({ mutationFn: async () => api.post('/api/v1/playbooks', { name: playbookName, domain, typical_requirements: [], recommended_features: [], common_integrations: [], security_checklist: [], deployment_checklist: [], questions: [] }), onSuccess: () => { client.invalidateQueries({ queryKey: ['playbooks'] }); setPlaybookName(''); setDomain('') } })
  const apply = useMutation({ mutationFn: async (id: string) => api.post(`/api/v1/playbooks/${id}/apply/${meetingId}`), onSuccess: (response) => setMessage(`${response.data.applied_questions} playbook questions added to the meeting.`), onError: () => setMessage('Enter a valid meeting ID before applying a playbook.') })
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Workspace Intelligence</h1><p className="mt-2 text-sm text-slate-600">Personalize discovery recommendations with workspace knowledge, reusable playbooks, and learned preferences.</p></div><section className="rounded-lg border bg-white p-4"><h2 className="font-semibold">Upload knowledge</h2><div className="mt-3 flex flex-wrap gap-3"><input type="file" accept=".pdf,.docx,.txt,.md,.markdown" onChange={(event) => setFile(event.target.files?.[0] || null)} /><button className="rounded bg-slate-900 px-3 py-2 text-white disabled:opacity-50" disabled={!file || upload.isPending} onClick={() => upload.mutate()}>{upload.isPending ? 'Indexing...' : 'Upload and index'}</button></div>{message && <p className="mt-2 text-sm text-slate-600">{message}</p>}<div className="mt-4 space-y-2">{documents.data?.map((item) => <p key={item.id} className="rounded border p-2 text-sm">{item.file_name} <span className="text-slate-500">· {item.status}</span></p>)}</div></section><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-lg border bg-white p-4"><h2 className="font-semibold">Workspace memory</h2><div className="mt-3 space-y-2">{memory.data?.map((item) => <article key={item.id} className="rounded border p-3"><p className="font-medium capitalize">{item.category.replaceAll('_', ' ')}</p><p className="text-sm text-slate-600">{item.value}</p><p className="text-xs text-slate-500">{Math.round(item.confidence_score * 100)}% confidence · {item.source}</p></article>) || <p className="text-sm text-slate-500">Learning starts from approved requirements and uploaded documents.</p>}</div></section><section className="rounded-lg border bg-white p-4"><h2 className="font-semibold">AI playbooks</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><input className="rounded border p-2" placeholder="Playbook name" value={playbookName} onChange={(event) => setPlaybookName(event.target.value)} /><input className="rounded border p-2" placeholder="Domain (e.g. FinTech)" value={domain} onChange={(event) => setDomain(event.target.value)} /></div><button className="mt-2 rounded border px-3 py-2 text-sm" disabled={!playbookName || !domain} onClick={() => create.mutate()}>Create playbook</button><input className="mt-4 w-full rounded border p-2" placeholder="Meeting ID to apply a playbook" value={meetingId} onChange={(event) => setMeetingId(event.target.value)} /><div className="mt-3 space-y-2">{playbooks.data?.map((item) => <article key={item.id} className="rounded border p-3"><p className="font-medium">{item.name}</p><p className="text-sm text-slate-600">{item.domain}</p><button className="mt-2 rounded border px-2 py-1 text-sm" onClick={() => apply.mutate(item.id)}>Apply to meeting</button></article>)}</div></section></div></div>
}
